version: "3"
services:
  hotchocolate-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_JAR_URL=https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/496/downloads/paper-1.20.4-496.jar
    ports:
      - 25565:25565
