name: Build artifacts and publish as GitHub release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2
      - name: Install curl
        run: sudo apt install curl
      - name: Install git
        run: sudo apt install git
      - name: Install OpenJDK 21
        run: sudo apt install openjdk-21-jdk-headless
      - name: Set OpenJDK 21 as default
        run: sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java
      - name: Install Maven
        run: sudo apt install maven
      - name: Run BuildTools
        run: util/runBuildTools.sh
      - name: Run Gradle build
        run: ./gradlew clean build
      - name: Read source branch version
        run: echo "VERSION=$(cat build.gradle | grep 'version = ' | cut -d'"' -f2)" >> $GITHUB_ENV
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$VERSION" --repo="$GITHUB_REPOSITORY" --title="Release $VERSION" --generate-notes --latest "./build/libs/HotChocolate-$VERSION.jar"
