name: Check for successful compilation

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2
      - name: Read source branch version
        id: branch
        run: echo version=$(cat build.gradle | grep -iE 'version = "([0-9]+(\\.[0-9]+)+)"' | cut -d'"' -f2) >> $GITHUB_ENV
      - name: Install curl
        run: sudo apt install curl
      - name: Install git
        run: sudo apt install git
      - name: Install OpenJDK 21
        run: sudo apt install openjdk-21-jdk-headless
      - name: Set OpenJDK 21 as default
        run: sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java
      - name: Install Maven
        run: sudo apt install maven
      - name: Run BuildTools
        run: util/runBuildTools.sh
      - name: Run Gradle build
        run: ./gradlew clean build
